# Generated by Django 2.2.3 on 2019-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='设备代号')),
                ('IMEI', models.CharField(max_length=100)),
                ('stage', models.CharField(blank=True, default='', max_length=100, verbose_name='阶段')),
                ('owner', models.CharField(max_length=100, verbose_name='保管人')),
                ('borrower', models.CharField(default='', max_length=50, verbose_name='借用人')),
                ('borrow_date', models.DateTimeField(null=True, verbose_name='借用日期')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
