# Generated by Django 2.2.3 on 2019-08-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_manage_plat', '0002_auto_20190813_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='IMEI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.CharField(default='', max_length=100, verbose_name='保管人'),
        ),
    ]
