# Generated by Django 2.2.3 on 2019-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_manage_plat', '0003_auto_20190813_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='borrower',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='借用人'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='阶段'),
        ),
    ]
