# Generated by Django 2.2.3 on 2019-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_manage_plat', '0004_auto_20190815_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='借用日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='borrower',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='借用人'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='阶段'),
        ),
    ]
